### ISSUE TITLE
can you  help to provide your trained weight model

### ISSUE THREAD

**Issue by zmy328** [tinyalpha/MM2021-Robust-Logo-Detection#1]
because I have not more GPU,I want to use your weight to train my task. 

Can you provide model files for the preliminary and finals respectively？
Thank  you very much .
My email is 363746924@qq.com.

**Comment by chenhang98** [comment]
You can download them from the following links:
- preliminary round: https://cloud.tsinghua.edu.cn/f/cc52ba6381b443d799b6/?dl=1
- final round: https://cloud.tsinghua.edu.cn/f/5761eecb5d134cb2a986/?dl=1
